services:
    _defaults:
        autowire: true
        public: false

    OxidEsales\EshopCommunity\Internal\Setup\User\AdminUserInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\User\AdminUserService