services:
    _defaults:
        autowire: true
        public: false

    OxidEsales\EshopCommunity\Internal\Setup\Database\DbServiceInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\Database\DbService